nelmio_api_doc:
    documentation:
        info:
            title: Cords
#            description: Cords
#            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!_error/)(?!api/.*$)
